#!/bin/bash

#
# This script checks if the nf_conntrack table is running full.
#

WARN=70
CRIT=80

# check for dependencies

if [ ! -f /proc/sys/net/netfilter/nf_conntrack_count ]; then
  # expect nt_conntrack not to be used
  exit 0
fi

connections=$(cat /proc/sys/net/netfilter/nf_conntrack_count)
max_connections=$(cat /proc/sys/net/netfilter/nf_conntrack_max)

warn=$(awk -v warn=$WARN -v max_connections=$max_connections 'BEGIN {print int(max_connections * warn / 100)}')
crit=$(awk -v crit=$CRIT -v max_connections=$max_connections 'BEGIN {print int(max_connections * crit / 100)}')

if [ $connections -lt $warn ]
then
  echo "0 nf_conntrack connections=$connections;$warn;$crit;$max_connections $connections/$max_connections connections"
elif [ $connections -ge $warn ] && [ $connections -lt $crit ]
then
  echo "1 nf_conntrack connections=$connections;$warn;$crit;$max_connections nf_conntrack filled by at least $warn % - $connections/$max_connections connections - consider raising net.netfilter.nf_conntrack_max"
elif [ $connections -ge $crit ]
then
  echo "2 nf_conntrack connections=$connections;$warn;$crit;$max_connections nf_conntrack filled by at least $crit % - $connections/$max_connections connections - consider raising net.netfilter.nf_conntrack_max"
else
  echo "3 nf_conntrack connections=$connections unknown"

fi

exit 0
